### PR TITLE
add django 3.2 support

### LINKED ISSUE #27: Upgrade to django 3.2
This plugin needs to work with the same version of django as edx-platform. 

#### Acceptance Criteria:

- [ ] test django 3.2 upgrade
- [ ] test with maple branch of edx-platform
- [ ] review any deprecation warnings for related libraries

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Tickets
fixes #27

add django 3.2 support

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1: looks good to me

**Comment by umarmughal824** [comment]
@blarghmatey have you tested it too?

**Comment by blarghmatey** [comment]
I haven't tested it yet but once we get it published I can update the version used for building our Maple images and will test it there.

**Comment by umarmughal824** [comment]
> I haven't tested it yet but once we get it published I can update the version used for building our Maple images and will test it there.

sure, makes sense

**Pull request merged**
